In [1]:
from google.colab import files

uploaded = files.upload()

Saving time_series_60min_singleindex.csv to time_series_60min_singleindex.csv

In [17]:
import pandas as pd
import numpy as np

df = pd.read_csv('time_series_60min_singleindex.csv')

energy = pd.DataFrame()

energy['date'] = pd.to_datetime(df['utc_timestamp'])
energy['price'] = df['DE_LU_price_day_ahead']

energy = energy.dropna()
energy = energy.set_index('date')

print(energy.shape)
energy.head()

(17540, 1)

                           price
date
2018-09-30 23:00:00+00:00  56.10
2018-10-01 00:00:00+00:00  51.41
2018-10-01 01:00:00+00:00  47.38
2018-10-01 02:00:00+00:00  47.59
2018-10-01 03:00:00+00:00  51.61

In [18]:
#returns
energy['return'] = energy['price'].pct_change()

energy = energy.replace(
    [np.inf, -np.inf],
    np.nan
)

energy = energy.dropna()

print(energy.shape)

energy['return'].describe()

(17533, 2)

count    17533.000000
mean        -0.076576
std         40.502677
min      -3744.000000
25%         -0.070117
50%         -0.010846
75%          0.061641
max       1303.000000
Name: return, dtype: float64

In [19]:
#stylized facts
from scipy.stats import skew, kurtosis

print(
    "Skew:",
    skew(energy['return'])
)

print(
    "Kurtosis:",
    kurtosis(energy['return'])
)

Skew: -55.72422324862008
Kurtosis: 5017.58000563617

In [20]:
#ARCH Test
from statsmodels.stats.diagnostic import het_arch

test = het_arch(
    energy['return']
)

print(test)

(np.float64(0.04480692473037784), np.float64(0.9999999999538376), 0.004477891184673421, 0.9999999999539291)

Βλέπουμε:

mean = -0.076
std = 40.5
min = -3744
max = 1303
skew = -55.7
kurtosis = 5017

Αυτά είναι εξωπραγματικά μεγάλα.

Ο λόγος είναι ότι υπάρχουν πολλές ώρες με τιμές πολύ κοντά στο μηδέν ή αρνητικές τιμές.

Παράδειγμα:

Price(t-1)=0.01
Price(t)=13

τότε:

return=(13-0.01)/0.01=1299

οπότε καταστρέφεται όλη η κατανομή.

Το σημαντικό εύρημα

Το ARCH test βγήκε:

p-value ≈ 1

που είναι επίσης ύποπτο και συμβαίνει ακριβώς επειδή τα returns έχουν γίνει ακραία.

Για το project θα χρησιμοποιήσουμε την κλασική προσέγγιση των electricity markets:
Price differences

In [21]:
energy = pd.DataFrame()

energy['date'] = pd.to_datetime(df['utc_timestamp'])
energy['price'] = df['DE_LU_price_day_ahead']

energy = energy.dropna()
energy = energy.set_index('date')

energy['return'] = energy['price'].diff()

energy = energy.dropna()

print(
    energy['return']
    .describe()
)

count    17539.000000
mean        -0.001237
std          5.551050
min       -101.910000
25%         -2.445000
50%         -0.320000
75%          2.095000
max        109.230000
Name: return, dtype: float64

In [22]:
from scipy.stats import skew, kurtosis

print(
    "Skew:",
    skew(energy['return'])
)

print(
    "Kurtosis:",
    kurtosis(energy['return'])
)

Skew: 0.48566319834168453
Kurtosis: 26.21171337626122

In [23]:
from statsmodels.stats.diagnostic import het_arch

print(
    het_arch(
        energy['return']
    )
)

(np.float64(3765.0995885891107), np.float64(0.0), 479.2029339170656, 0.0)

1. Skewness = 0.49
Υπάρχει μικρή θετική ασυμμετρία.

Αυτό σημαίνει ότι υπάρχουν περισσότεροι θετικοί ακραίοι κραδασμοί από ό,τι θα περίμενε μια κανονική κατανομή.

2. Kurtosis = 26.2

Αυτό είναι εξαιρετικά σημαντικό.

Η κανονική κατανομή έχει:

Kurtosis = 3

Εσύ έχεις:

Kurtosis = 26.2

που σημαίνει:

fat tails, δηλαδή ακραία γεγονότα εμφανίζονται πολύ συχνότερα από ό,τι προβλέπει η κανονική κατανομή.

Αυτό είναι χαρακτηριστικό των:

financial markets,
electricity markets,
commodity markets.
3. ARCH test

Έχουμε:

p-value = 0

δηλαδή απορρίπτουμε πλήρως τη μηδενική υπόθεση.

Με απλά λόγια:

η μεταβλητότητα εμφανίζεται σε clusters.

In [26]:
!pip install arch

#GARCH(1,1)
from arch import arch_model

garch = arch_model(
    energy['return'],
    mean='Constant',
    vol='GARCH',
    p=1,
    q=1,
    dist='t'
)

garch_fit = garch.fit()

print(garch_fit.summary())

Collecting arch
  Downloading arch-8.0.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from arch) (2.0.2)
Requirement already satisfied: pandas>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from arch) (2.2.2)
Requirement already satisfied: scipy>=1.8 in /usr/local/lib/python3.12/dist-packages (from arch) (1.16.3)
Requirement already satisfied: statsmodels>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from arch) (0.14.6)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from arch) (26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->arch) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->arch) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->arch) (2026.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.13.0->arch) (1.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->arch) (1.17.0)
Downloading arch-8.0.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (981 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.3/981.3 kB 14.9 MB/s eta 0:00:00
Installing collected packages: arch
Successfully installed arch-8.0.0
Iteration:      1,   Func. Count:      7,   Neg. LLF: 560199.4189588731
Iteration:      2,   Func. Count:     16,   Neg. LLF: 279491.29844510445
Iteration:      3,   Func. Count:     23,   Neg. LLF: 70357.54726588774
Iteration:      4,   Func. Count:     30,   Neg. LLF: 67965.81476287656
Iteration:      5,   Func. Count:     40,   Neg. LLF: 66125.15954491968
Iteration:      6,   Func. Count:     47,   Neg. LLF: 50560.33669464038
Iteration:      7,   Func. Count:     53,   Neg. LLF: 64228.15637981024
Iteration:      8,   Func. Count:     60,   Neg. LLF: 65806.19242493853
Iteration:      9,   Func. Count:     67,   Neg. LLF: 50635.44189670287
Iteration:     10,   Func. Count:     74,   Neg. LLF: 50273.356743132405
Iteration:     11,   Func. Count:     80,   Neg. LLF: 50232.88825909324
Iteration:     12,   Func. Count:     86,   Neg. LLF: 50205.320732868735
Iteration:     13,   Func. Count:     92,   Neg. LLF: 50184.72012842457
Iteration:     14,   Func. Count:     98,   Neg. LLF: 50176.54659241806
Iteration:     15,   Func. Count:    104,   Neg. LLF: 50164.98392511593
Iteration:     16,   Func. Count:    110,   Neg. LLF: 50158.84143203295
Iteration:     17,   Func. Count:    116,   Neg. LLF: 50151.30806728936
Iteration:     18,   Func. Count:    122,   Neg. LLF: 50151.168733548715
Iteration:     19,   Func. Count:    128,   Neg. LLF: 50151.13854726628
Iteration:     20,   Func. Count:    134,   Neg. LLF: 50151.13691131537
Iteration:     21,   Func. Count:    140,   Neg. LLF: 50151.13656035933
Iteration:     22,   Func. Count:    146,   Neg. LLF: 50151.136554994475
Iteration:     23,   Func. Count:    151,   Neg. LLF: 50151.13655499438
Optimization terminated successfully    (Exit mode 0)
            Current function value: 50151.136554994475
            Iterations: 23
            Function evaluations: 151
            Gradient evaluations: 23
                        Constant Mean - GARCH Model Results
====================================================================================
Dep. Variable:                       return   R-squared:                       0.000
Mean Model:                   Constant Mean   Adj. R-squared:                  0.000
Vol Model:                            GARCH   Log-Likelihood:               -50151.1
Distribution:      Standardized Student's t   AIC:                           100312.
Method:                  Maximum Likelihood   BIC:                           100351.
                                              No. Observations:                17539
Date:                      Fri, Jul 03 2026   Df Residuals:                    17538
Time:                              10:48:15   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu            -0.6113  2.804e-02    -21.796 2.520e-105 [ -0.666, -0.556]
                             Volatility Model
==========================================================================
                 coef    std err          t      P>|t|    95.0% Conf. Int.
--------------------------------------------------------------------------
omega          7.4745      0.320     23.324 2.523e-120   [  6.846,  8.103]
alpha[1]       0.8911  2.848e-02     31.288 6.890e-215   [  0.835,  0.947]
beta[1]        0.1089  9.115e-03     11.944  7.015e-33 [9.100e-02,  0.127]
                              Distribution
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
nu             3.6626  7.419e-02     49.366      0.000 [  3.517,  3.808]
========================================================================

Covariance estimator: robust

Γιατί χρησιμοποιούμε dist='t';

Επειδή μόλις αποδείξαμε ότι έχουμε:

Kurtosis = 26

δηλαδή fat tails.

Η Student-t κατανομή είναι σχεδόν πάντα καλύτερη από την Gaussian στις αγορές ενέργειας.

Τι μας λέει το μοντέλο;
1. Volatility persistence

Το πρώτο πράγμα που κοιτάμε πάντα είναι:

α + β

Εδώ έχουμε:

0.891 + 0.109 = 1.000

Αυτό είναι εξαιρετικά ενδιαφέρον.

Σημαίνει:

η μεταβλητότητα στην αγορά ηλεκτρικής ενέργειας είναι σχεδόν πλήρως persistent.

Με άλλα λόγια:

ένα μεγάλο shock σήμερα
↓
επηρεάζει τη μεταβλητότητα για πολλές ώρες ή ημέρες
2. Shock reaction

Το:

alpha = 0.891

είναι πολύ υψηλό.

Αυτό σημαίνει:

η αγορά αντιδρά εξαιρετικά έντονα σε νέα πληροφορία.

Αυτό είναι χαρακτηριστικό των electricity markets λόγω:

renewable intermittency,
demand spikes,
transmission constraints.
3. Heavy tails

Το:

nu = 3.66

είναι ίσως το πιο ενδιαφέρον αποτέλεσμα.

Για Student-t:

ν → ∞

πλησιάζει την Gaussian.

Εσύ έχεις:

ν = 3.66

δηλαδή:

εξαιρετικά βαριές ουρές.

Αυτό επιβεβαιώνει πλήρως το αποτέλεσμα της kurtosis=26.

In [27]:
#Model 2- EGARCH(1,1)
egarch = arch_model(
    energy['return'],
    mean='Constant',
    vol='EGARCH',
    p=1,
    q=1,
    dist='t'
)

egarch_fit = egarch.fit()

print(egarch_fit.summary())

Iteration:      1,   Func. Count:      7,   Neg. LLF: 346717.00895076914
Iteration:      2,   Func. Count:     20,   Neg. LLF: 327194.50550229504
Iteration:      3,   Func. Count:     30,   Neg. LLF: 366481.96833794034
Iteration:      4,   Func. Count:     39,   Neg. LLF: 73379.21213584727
Iteration:      5,   Func. Count:     46,   Neg. LLF: 65767.39914359624
Iteration:      6,   Func. Count:     53,   Neg. LLF: 63851.08635958007
Iteration:      7,   Func. Count:     60,   Neg. LLF: 58752.02896824934
Iteration:      8,   Func. Count:     67,   Neg. LLF: 63416.54254112425
Iteration:      9,   Func. Count:     74,   Neg. LLF: 63349.77277821703
Iteration:     10,   Func. Count:     81,   Neg. LLF: 63262.73166917103
Iteration:     11,   Func. Count:     88,   Neg. LLF: 63150.739643912944
Iteration:     12,   Func. Count:     95,   Neg. LLF: 54344.01315752279
Iteration:     13,   Func. Count:    102,   Neg. LLF: 50170.96484567476
Iteration:     14,   Func. Count:    108,   Neg. LLF: 50206.51419783039
Iteration:     15,   Func. Count:    115,   Neg. LLF: 50163.73974784744
Iteration:     16,   Func. Count:    121,   Neg. LLF: 50161.93662379911
Iteration:     17,   Func. Count:    127,   Neg. LLF: 50159.8206785144
Iteration:     18,   Func. Count:    133,   Neg. LLF: 50157.598888619585
Iteration:     19,   Func. Count:    139,   Neg. LLF: 50154.750073089
Iteration:     20,   Func. Count:    145,   Neg. LLF: 50152.781517096664
Iteration:     21,   Func. Count:    151,   Neg. LLF: 50152.26297552477
Iteration:     22,   Func. Count:    157,   Neg. LLF: 50152.23031055276
Iteration:     23,   Func. Count:    163,   Neg. LLF: 50152.22788884506
Iteration:     24,   Func. Count:    169,   Neg. LLF: 50152.2262901846
Iteration:     25,   Func. Count:    175,   Neg. LLF: 50152.22627688203
Iteration:     26,   Func. Count:    182,   Neg. LLF: 50152.22622965324
Iteration:     27,   Func. Count:    189,   Neg. LLF: 50152.22620333018
Iteration:     28,   Func. Count:    195,   Neg. LLF: 50152.22622193859
Iteration:     29,   Func. Count:    202,   Neg. LLF: 50152.226262032316
Optimization terminated successfully    (Exit mode 0)
            Current function value: 50152.22620151537
            Iterations: 29
            Function evaluations: 204
            Gradient evaluations: 29
                        Constant Mean - EGARCH Model Results
====================================================================================
Dep. Variable:                       return   R-squared:                       0.000
Mean Model:                   Constant Mean   Adj. R-squared:                  0.000
Vol Model:                           EGARCH   Log-Likelihood:               -50152.2
Distribution:      Standardized Student's t   AIC:                           100314.
Method:                  Maximum Likelihood   BIC:                           100353.
                                              No. Observations:                17539
Date:                      Fri, Jul 03 2026   Df Residuals:                    17538
Time:                              10:50:36   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu            -0.6200  7.317e-03    -84.734      0.000 [ -0.634, -0.606]
                            Volatility Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
omega          1.7925  5.397e-02     33.210 7.851e-242 [  1.687,  1.898]
alpha[1]       1.2205  3.269e-02     37.341 3.521e-305 [  1.156,  1.285]
beta[1]        0.4984  1.326e-02     37.583 4.150e-309 [  0.472,  0.524]
                              Distribution
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
nu             3.1747  8.335e-02     38.090      0.000 [  3.011,  3.338]
========================================================================

Covariance estimator: robust

Ερμηνεία EGARCH
Mean
μ = -0.620

Παρόμοιο με το GARCH.

Volatility persistence

Έχουμε:

beta = 0.498

που δείχνει μέτρια persistence.

Shock response
alpha = 1.220

Πολύ μεγάλο.

Αυτό σημαίνει ότι η μεταβλητότητα επηρεάζεται έντονα από νέα shocks.

Heavy tails
nu = 3.17

Ακόμη μικρότερο από το GARCH:

GARCH : 3.66
EGARCH: 3.17

Άρα το μοντέλο συνεχίζει να βλέπει πολύ βαριές ουρές.

Το σημαντικό εύρημα

Παρατηρώ ότι δεν εμφανίζεται:

gamma[1]

Η παράμετρος αυτή είναι η ασυμμετρία (leverage effect).

Αυτό σημαίνει ότι το συγκεκριμένο EGARCH specification δεν εκτίμησε ασύμμετρο όρο ή ότι δεν τον ζητήσαμε.

In [28]:
#GJR-GARCH
gjr = arch_model(
    energy['return'],
    mean='Constant',
    vol='GARCH',
    p=1,
    o=1,      # asymmetry term
    q=1,
    dist='t'
)

gjr_fit = gjr.fit()

print(gjr_fit.summary())

Iteration:      1,   Func. Count:      8,   Neg. LLF: 166201.63336964458
Iteration:      2,   Func. Count:     19,   Neg. LLF: 176319.67293440012
Iteration:      3,   Func. Count:     27,   Neg. LLF: 66130.8080365581
Iteration:      4,   Func. Count:     35,   Neg. LLF: 65859.3256405964
Iteration:      5,   Func. Count:     43,   Neg. LLF: 51059.299689544256
Iteration:      6,   Func. Count:     51,   Neg. LLF: 65712.51470061812
Iteration:      7,   Func. Count:     59,   Neg. LLF: 50865.61311805324
Iteration:      8,   Func. Count:     67,   Neg. LLF: 65473.60079891846
Iteration:      9,   Func. Count:     75,   Neg. LLF: 50090.964180338924
Iteration:     10,   Func. Count:     82,   Neg. LLF: 50034.48055899313
Iteration:     11,   Func. Count:     89,   Neg. LLF: 50789.36372507749
Iteration:     12,   Func. Count:     97,   Neg. LLF: 49985.3301365055
Iteration:     13,   Func. Count:    104,   Neg. LLF: 49980.405679093084
Iteration:     14,   Func. Count:    111,   Neg. LLF: 49971.381981090104
Iteration:     15,   Func. Count:    118,   Neg. LLF: 49970.2670211304
Iteration:     16,   Func. Count:    125,   Neg. LLF: 49969.62603993051
Iteration:     17,   Func. Count:    132,   Neg. LLF: 49969.524674706976
Iteration:     18,   Func. Count:    139,   Neg. LLF: 49969.5064310002
Iteration:     19,   Func. Count:    146,   Neg. LLF: 49969.505295575276
Iteration:     20,   Func. Count:    153,   Neg. LLF: 49969.50483058731
Iteration:     21,   Func. Count:    160,   Neg. LLF: 49969.504822354356
Iteration:     22,   Func. Count:    166,   Neg. LLF: 49969.50482235445
Optimization terminated successfully    (Exit mode 0)
            Current function value: 49969.504822354356
            Iterations: 22
            Function evaluations: 166
            Gradient evaluations: 22
                      Constant Mean - GJR-GARCH Model Results
====================================================================================
Dep. Variable:                       return   R-squared:                       0.000
Mean Model:                   Constant Mean   Adj. R-squared:                  0.000
Vol Model:                        GJR-GARCH   Log-Likelihood:               -49969.5
Distribution:      Standardized Student's t   AIC:                           99951.0
Method:                  Maximum Likelihood   BIC:                           99997.6
                                              No. Observations:                17539
Date:                      Fri, Jul 03 2026   Df Residuals:                    17538
Time:                              10:53:01   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu            -0.6166  2.757e-02    -22.363 8.935e-111 [ -0.671, -0.563]
                            Volatility Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
omega          6.1086      0.268     22.799 4.640e-115 [  5.583,  6.634]
alpha[1]       1.0000  3.234e-02     30.917 6.986e-210 [  0.937,  1.063]
gamma[1]      -0.6301  3.692e-02    -17.067  2.616e-65 [ -0.703, -0.558]
beta[1]        0.2003  1.300e-02     15.402  1.586e-53 [  0.175,  0.226]
                              Distribution
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
nu             3.9315  8.338e-02     47.153      0.000 [  3.768,  4.095]
========================================================================

Covariance estimator: robust

Πρώτο συμπέρασμα

Το GJR-GARCH είναι ξεκάθαρα το καλύτερο μοντέλο:

AIC improvement ≈ 361 μονάδες

Αυτό είναι τεράστια βελτίωση.

Άρα:

Η μεταβλητότητα της γερμανικής αγοράς ηλεκτρισμού είναι ασύμμετρη.

Ανάλυση των παραμέτρων
ω = 6.11

Είναι το long-run variance component.

α = 1.00
alpha = 1

Αυτό είναι εξαιρετικά υψηλό.

Σημαίνει:

η αγορά αντιδρά σχεδόν άμεσα και πολύ έντονα στα νέα shocks.

γ = -0.63

Αυτό είναι το σημαντικότερο αποτέλεσμα όλου του project.

Έχουμε:

gamma = -0.63
p-value << 0.001

δηλαδή ισχυρή ασυμμετρία.

Πώς ερμηνεύεται το αρνητικό gamma;

Στις μετοχές συνήθως έχουμε:

gamma > 0

(οι αρνητικές αποδόσεις αυξάνουν τη μεταβλητότητα).

Στην ηλεκτρική ενέργεια όμως συχνά συμβαίνει το αντίθετο:

positive price shocks
       >
negative price shocks

Δηλαδή:

shortages,
demand spikes,
renewable production failures,

προκαλούν μεγαλύτερη μεταβλητότητα από ό,τι οι αρνητικές τιμές.

Αυτό είναι απολύτως συμβατό με τη βιβλιογραφία των power markets.

β = 0.20

Η persistence είναι αρκετά μικρότερη από το απλό GARCH.

Αυτό σημαίνει ότι μεγάλο μέρος της persistence που βλέπαμε πριν εξηγείται πλέον από την ασυμμετρία.

ν = 3.93

Παραμένουν εξαιρετικά βαριές ουρές:

Student-t ν ≈ 4

οπότε έχουμε ισχυρή ένδειξη για:

price spikes,
extreme events,
market stress periods.

The German electricity market exhibits significant volatility clustering, heavy tails and asymmetric volatility dynamics. Among the estimated models, the GJR-GARCH specification provided the best fit according to the AIC criterion, indicating that positive price shocks generate stronger volatility responses than negative shocks.